server:
  port:
  host:
  endpoint:

database:
  url:

ethereum:
  rpc:
  chain_id:
  token_address:
  stake_wallet_address:

aws:
  region: us-west-2
  bucket_name: dev-parity-docker-images
scheduler:
  interval:
